# monitor.alsa.rules = [
#   {
#     matches = [
#       { node.name = "alsa_input.usb-Focusrite_Scarlett_2i2_4th_Gen_S2JYTQ63508147-00.pro-input-0" }
#     ]
#     actions = {
#       update-props = {
#         api.acp.pro-channels = 1
#         audio.channels = 1
#         audio.position = "MONO"
#         node.nick = "TRALALA"
#       }
#     }
#   }
# ]

