monitor.alsa.rules = [
  {
    matches = [
      { device.name = "~alsa_card.usb-Focusrite_Scarlett_2i2_4th_Gen.*" }
    ]
    actions = {
      update-props = {
        device.profile.pro = true
      }
    }
  }
]
