monitor.alsa.rules = [
  {
    matches = [
      { "node.name" = "~alsa_input.usb-Focusrite_Scarlett_2i2_4th_Gen.*" }
      # { "node.name" = "~alsa_output.usb-Focusrite_Scarlett_2i2_4th_Gen.*" }
    ]
    actions = {
      update-props = {
        api.alsa.period-size = 128
        api.alsa.period-num = 3
      }
    }
  }
]
