# NOT WORKING FOR SOME REASON - DOING THIS IN A SCRIPT
# 
# override.wireplumber.rules = [
#   {
#     matches = [
#       {
#         # Match using the node property directly since it's an isolated JACK DSP node
#         "node.name" = "OBS Studio: sm7 JCK no effects"
#       },
#       {
#         "node.name" = "OBS Studio: sm7 JCK effects"
#       }
#     ]
#     actions = {
#       update-props = {
#         "target.object" = "My 2i2_MONO"
#         "node.autoconnect" = true
#         "log.level" = "3"
#       }
#     }
#   }
# ]
