# Set font family
# font_family FiraCode Nerd Font

# Set default font size
font_size 16

# Close current tab with Ctrl+W
map ctrl+w close_window
scrollback_lines 10000000
# TODO think about how to make ctrl+V consistent
# ctrl+V is problematic because of nvim
map ctrl+c copy_or_interrupt
