context.modules = [
{
name = libpipewire-module-loopback

args = {
    node.description = "My 2i2 input 1"

    capture.props = {
        audio.position = [ MONO ]
        node.passive = true
        node.target = "alsa_input.usb-Focusrite_Scarlett_2i2_4th_Gen_S2JYTQ63508147-00.pro-input-0"
        stream.dont-remix = true
    }
    playback.props = {
        audio.position = [ MONO ]
        media.class = "Audio/Source"
        node.name = "My 2i2_MONO"
    }
}
}
]
