context.modules = [
{
"name": "libpipewire-module-loopback"

"args": {
    node.description: "Discord_virt_sink"

    capture.props: {
        audio.position: ["FL", "FR"]
        media.class: "Audio/Sink"
        node.linger: true
        node.name: "Discord_virtual_sink"
        stream.dont-remix: true
    },
    playback.props: {
        audio.position: ["FL", "FR"]
        node.dont-fallback: true
        node.dont-reconnect: true
        node.linger: true
        node.name: "Discord_out"
        # TODO consider setting passive to false
        # https://gemini.google.com/share/877adc462c96
        node.passive: true
        stream.dont-remix: true
        target.object: "alsa_output.usb-Focusrite_Scarlett_2i2_4th_Gen_S2JYTQ63508147-00.pro-output-0"
    }
}
}
]
