context.modules = [
    { name = libpipewire-module-loopback
        args = {
            node.description = "Scarlett SM7B Mono"
            capture.props = {
                node.target = "alsa_input.usb-Focusrite_Scarlett_2i2_4th_Gen_S2JYTQ63508147-00.analog-surround-40"
                audio.position = [ FR ]
                stream.dont-remix = true
                node.passive = true
            }
            playback.props = {
                node.name = "Scarlett_SM7B_Virtual_Mic"
                media.class = "Audio/Source"
                audio.position = [ MONO ]
            }
        }
    }
]

