# pulse.properties = {
#     pulse.min.req          = 256/48000     # 5.3ms
#     pulse.default.req      = 256/48000     # 20 milliseconds
#     pulse.min.frag         = 256/48000     # 5.3ms
#     pulse.default.frag     = 512/48000   # 2 seconds
#     pulse.default.tlength  = 512/48000   # 2 seconds
#     pulse.min.quantum      = 256/48000     # 5.3ms
# }
 
